config/routes.rb
Rails.application.routes.draw do
	root to: 'welcome#index'
	get "main", to: "main#index"
	get "partner", to: "partner#index"
	resources :hotels
	resources :partner_sessions, only: [ :new, :create, :destroy ]

	get 'login'  => 'partner_sessions#new'
	get 'logout' => 'partner_sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hotel.rb
class Hotel < ApplicationRecord
end

app/models/partner.rb
class Partner < ApplicationRecord
  authenticates_with_sorcery!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
	include HotelsHelper
	
	before_filter :require_login
	
	def require_login
    	unless logged_in?
      		flash.notice = "You must be logged in to access this section"
      		redirect_to root_path
    	end
    end

	def new
		@hotel = Hotel.new
	end

	def index
		@hotels = Hotel.all
	end
	def create
  		@hotel = Hotel.new(hotel_params)
  		@hotel.save!

  		redirect_to partner_path
	end

	def destroy
		@hotel = Hotel.find(params[:id])
		@hotel.destroy
		flash.notice = "Hotel '#{@hotel.name}' Deleted!"

		redirect_to partner_path
	end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	def index

	end
end

app/controllers/partner_controller.rb
class PartnerController < ApplicationController
	before_filter :require_login
	
	def require_login
    	unless logged_in?
      		flash.notice = "You must be logged in to access this section"
      		redirect_to root_path
    	end
    end

	def index
		@hotel = Hotel.new
		@hotels = Hotel.all
	end
end

app/controllers/partner_sessions_controller.rb
class PartnerSessionsController < ApplicationController
  def new
  end

  def create
    if login(params[:email], params[:password])
      redirect_back_or_to(partner_path, notice: 'Logged in successfully.')
    else
      flash.now.alert = "Login failed."
      redirect_back_or_to(root_path, notice: 'Logged in failed.')
    end
  end

  def destroy
    logout
    redirect_to(:root, notice: 'Logged out!')
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
	def hotel_params
  		params.require(:hotel).permit(:name, :street_address, :phone, :city, :country, :state, :zip_code, :stars, :eco_rate)
	end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/partner_helper.rb
module PartnerHelper
end

app/helpers/partner_sessions_helper.rb
module PartnerSessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/hotels/_form.html.erb
<div class="hotel_form_wrapper">
  <p class="addhotel">Add a Hotel</p><br>
  <%= form_for (@hotel) do |f| %>
      <div class="singleformwrapper"><%= f.label :name, "Name" %><%= f.text_field :name %></div>
      <div class="singleformwrapper"><%= f.label :street_address, "Street Address"  %><%= f.text_field :street_address %></div>
      <div class="singleformwrapper"><%= f.label :city, "City" %><%= f.text_field :city %></div>
      <div class="singleformwrapper"><%= f.label :state, "State" %><%= f.text_field :state %></div>
      <div class="singleformwrapper"><%= f.label :country, "Country" %><%= f.text_field :country %></div>
      <div class="singleformwrapper"><%= f.label :zip_code, "Zip Code"  %><%= f.text_field :zip_code %></div>
      <div class="singleformwrapper"><%= f.label :phone, "Phone" %><%= f.text_field :phone %></div>
      <div class="singleformwrapper"><%= f.label :stars, "Stars" %><%= f.text_field :stars %></div>
      <div class="singleformwrapper"><%= f.label :eco_rate, "Eco Rate"  %><%= f.text_field :eco_rate %></div>
      <div class="submitwrapper">
        <%= f.submit 'Submit' %>
      </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GreenGoRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script>
  		$( function() {
    		$( "#datepickercheckin" ).datepicker();
   			$( "#datepickercheckout" ).datepicker();
 		} );
  	</script>
  </head>
  <p class="flash">
  	<%= flash.notice %>
  </p>
  <body>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<div class="logolink" ><%= link_to image_tag("greengo-logo.png"), main_path %></div>
<div class="container">
	<div class="mainwrapper">
		<div class="upperpartheading1">
			<form>
				<div class="group">
					<input class="animatedinput" type="text" required>
					<span class="highlighted"></span>
					<span class="bar" id="wherebar"></span>
					<label class="mainlabel">
						<pre>W  H  E  R  E  ?</pre>
					</label>
				</div>
			</form>
		</div>
		<div class="upperpartheading2">
			<form>
				<div class="group">
					<input class="animatedinput" type="text" id="datepickercheckin" required>
					<span class="highlighted"></span>
					<span class="bar"></span>
					<label class="mainlabel">
						<pre>C  H  E  C  K  I  N</pre>
					</label>
				</div>
			</form>
		</div>
		<div class="upperpartheading3">
			<form>
				<div class="group">
			    	<input class="animatedinput" type="text" id="datepickercheckout" required>
			    	<span class="highlighted"></span>
			    	<span class="bar"></span>
			    	<label class="mainlabel">
			    		<pre>C  H  E  C  K  O  U  T</pre>
			    	</label>
			    </div>
			</form>
		</div>
		<div class="upperpartheading4"><div class="howmanywrapper">
			<form>
				<div class="group">
					<input class="animatedinput" type="text" name="howmanyinputname" onclick="myFunction()" required>
					<span class="highlighted"></span>
					<span class="bar"></span>
					<label class="mainlabel">
						<pre>H  O  W    M  A  N  Y  ?</pre>
					</label>
				</div>
			</form>
		</div></div>
		<div class="upperpartheading5">
			<button class="searchbutton" type="button">SEARCH</button>
		</div>
	</div>
	<div class="mainborder"></div>
    <%= link_to image_tag("nature1.jpg"), main_path, class: "image1" %><!--
 --><%= link_to image_tag("nature2.jpg"), main_path, class: "image2" %><!--
 --><%= link_to image_tag("nature3.jpg"), main_path, class: "image3" %><!--
 --><%= link_to image_tag("nature4.jpg"), main_path, class: "image4" %><!--
 --><%= link_to image_tag("nature5.jpg"), main_path, class: "image5" %>
</div>

app/views/partner/index.html.erb
<%= render partial: 'hotels/form' %>
<br><p class="allhotels">All Hotels ( <%= @hotels.size %> )</p>
<div class="box-table">
	<table class="menutable">
		<col width="150">
  		<col width="150">
  		<col width="150">
  		<col width="150">
  		<col width="150">
  		<col width="150">
  		<col width="150">
  		<col width="150">
  		<col width="150">
  		<col width="150">
		<thead>
			<tr>
				<td>Name</td>
				<td>Street Address</td>
				<td>City</td>
				<td>State</td>
				<td>Country</td>
				<td>Zip Code</td>
				<td>Phone</td>
				<td>Stars</td>
				<td>Eco Rate</td>
				<td>Action Delete</td>
			</tr>
		</thead>
		<% @hotels.each do |hotel| %>
			<tr>
				<td class="hotel-name"><%= hotel.name %></td>
				<td class="hotel-street-address"><%= hotel.street_address %></td>
				<td class="hotel-city"><%= hotel.city %></td>
				<td class="hotel-state"><%= hotel.state %></td>
				<td class="hotel-country"><%= hotel.country %></td>
				<td class="hotel-zip"><%= hotel.zip_code %></td>
				<td class="hotel-phone"><%= hotel.phone %></td>
				<td class="hotel-stars"><%= hotel.stars %></td>
				<td class="hotel-eco-rate"><%= hotel.eco_rate %></td>
				<td class="hotel-delete"><%= link_to "Delete", hotel_path(hotel), method: :delete, data: {confirm: "Really delete the hotel?"} %></td>
			</tr>
		<% end %>
	</table>
</div>
<br>
<div class="logoutbuttonwrapper">
	<h6>
    	<% if logged_in? %>
      		<%= "Logged in as #{current_user.email}" %><br>
      		<%= link_to "Logout", logout_path %>
    	<% else %>
      		<%= link_to "Login", login_path %>
    	<% end %>
	</h6>
</div>

app/views/partner_sessions/new.html.erb
<div class="loginformwrapper">
<%= form_tag partner_sessions_path, method: :post do %>
  <div class="loginformwrapperfield">
    <%= label_tag :email %>
    <%= text_field_tag :email %>
    <br/>
  </div>
  <div class="loginformwrapperfield">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <br/>
  </div>
  <div class="loginformwrapperfieldaction">
    <%= submit_tag "Login" %>
  </div>
<% end %>

<%= link_to 'Back', root_path %>
</div>

app/views/welcome/index.html.erb
<div class="welcomelabelwrapper">
	<p class="mainwelcomelabel">Welcome to GreenGo</p>
</div>
<div class="welcomebuttonswrapper">
	<% if logged_in? %>
      		<%= link_to image_tag("partner200.jpg"), partner_path, class: "partnerimage" %>
      		<span class="welcomebuttonslabelpartner">Partner</span>
    <% else %>
      		<%= link_to image_tag("partner200.jpg"), root_path, class: "partnerimage" %>
      		<span class="welcomebuttonslabelpartner">Partner</span>
    <% end %>
	<%= link_to image_tag("hotel200.jpg"), main_path, class: "hotelimage" %>
	<span class="welcomebuttonslabelhotel">Hotel</span>
</div>
<div class="loginbuttonwrapper">
	<h6>
    	<% if logged_in? %>
      		<%= "Logged in as #{current_user.email}" %><br>
      		<%= link_to "Logout", logout_path %>
    	<% else %>
      		<%= link_to "Login", login_path %>
    	<% end %>
	</h6>
</div>